# Values to be stored in vault

codeExecutionEnvironmentsMongoRepository:
  connectionString: mongodb://JSCodeSandboxUser:StrongPassword123@localhost:62222/?authSource=JSCodeSandbox&authMechanism=SCRAM-SHA-256

codeExecutionsAuditMongoRepository:
  connectionString: mongodb://JSCodeSandboxUser:StrongPassword123@localhost:62222/?authSource=JSCodeSandbox&authMechanism=SCRAM-SHA-256
