# values.yaml

logLevel: Information

codeExecutionEnvironmentsMongoRepository:
  databaseName: JSCodeSandbox
  collectionName: CodeExecutionEnvironments

codeExecutionsAuditMongoRepository:
  databaseName: JSCodeSandbox
  collectionName: CodeExecutionsAudit

sesJsCodeExecutionService:
  environmentsBasePath: C:\Users\dmarra\source\jsenvironments

jsCodeSandbox:
  imagePullSecret: gitlab-registry-secret

customCa:
  enabled: false
  existingSecret: ""
  mountPath: ""
