apiVersion: v1
kind: Service
metadata:
  name: jscodesandbox
spec:
  ports:
   - port: 80           # External port (e.g., what clients connect to)
     targetPort: 8080   # Matches the containerPort in the Deployment
     protocol: TCP
     name: http
  selector:
    app: jscodesandbox
